name: Pull Request Check

on:
  pull_request:
    branches: [main, master]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Run linting
        run: npm run lint

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Run type check
        run: npm run type-check

      - name: Comment PR with results
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const fs = require('fs');
            let coverage = 'No coverage data available';

            try {
              const coverageFile = fs.readFileSync('./coverage/lcov.info', 'utf8');
              const lines = coverageFile.split('\n');
              const lf = lines.find(line => line.startsWith('LF:'));
              const lh = lines.find(line => line.startsWith('LH:'));
              
              if (lf && lh) {
                const totalLines = parseInt(lf.split(':')[1]);
                const hitLines = parseInt(lh.split(':')[1]);
                const percentage = ((hitLines / totalLines) * 100).toFixed(1);
                coverage = `${percentage}% (${hitLines}/${totalLines} lines)`;
              }
            } catch (error) {
              console.log('Could not read coverage file');
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## ✅ Quality Check Results

            - **Formatting**: ✅ Passed
            - **Linting**: ✅ Passed  
            - **Tests**: ✅ Passed
            - **Type Check**: ✅ Passed
            - **Coverage**: ${coverage}

            All checks passed! 🎉`
            });
